### PR TITLE
Revert behavior to fix failing tests. Add arrow key support. Fixes #65, #54, #63, #44

### LINKED ISSUE #65: Wrong behaviour according to CSS editor drafts?
According to:
https://drafts.csswg.org/selectors-4/#the-focusring-pseudo

The pseudo class focus-ring should always be applied on focus to input elements to indicate a where the user should enter text.
However, it should applied if I select e.g. a link / button element using the keyboard (tab button). 
However, if I do so with the mouse it shouldn't be applied. The reason is that if I tab through links using the keyboard I need to know WHERE I am but I don't need that information if I click on the element.
Of course, it depends on the corresponding browser's heuristics but that part is mentioned as example there.

### PR DESCRIPTION
**Pull request by robdodson**
This reverts the behavior that's currently on master because it was breaking mouse focus and causing most of the tests to fail. It uses a different approach to address the URL bar issue from #15 and adds support for arrow keys to address #54, #63.

This also removes the polyfill for classList. This is in accordance with the W3C's new [Polyfill guidance](https://www.w3.org/2001/tag/doc/polyfills/#don-t-serve-unnecessary-polyfills) which suggests that polyfills should not bundle other polyfills. Instead, we'll update our docs to mention that the polyfill depends on classList and users should use a service like polyfill.io to add it.

@kloots FYI because I needed to back out the previous `onKeyUp` change.

### CODE REVIEW

File: src/focus-ring.js [hunk 1]
```diff
@@ -70,32 +65,43 @@ function init() {
...
-   *    browser chrome into the document. (For more, see issue #15)
+   * On `keydown`, set `hadKeyboardEvent`, add `focus-ring` class if the
+   * key was Tab/Shift-Tab or Arrow Keys.
    * @param {Event} e
    */
-  function onKeyUp(e) {
+  function onKeyDown(e) {
+    const allowedKeys = [9, 37, 38, 39, 40];
+
+    // If the user is holding down a modifier key, abort.
```
Comment (alice) [inline src/focus-ring.js]: Suggestion: "Ignore keypresses if the user is holding down a modifier key"

File: src/focus-ring.js [hunk 2]
```diff
@@ -70,32 +65,43 @@ function init() {
...
     if (e.altKey || e.ctrlKey || e.metaKey)
       return;
 
-    if (e.keyCode != 9)
+    // If the key can't be found in the list of allowed keys, abort.
```
Comment (alice) [inline src/focus-ring.js]: Suggestion: "Ignore keypresses which aren't related to keyboard navigation."

File: src/focus-ring.js [hunk 3]
```diff
@@ -70,32 +65,43 @@ function init() {
...
+    if (allowedKeys.indexOf(e.keyCode) === -1)
+      return;
+
+    hadKeyboardEvent = true;
+  }
+
+  /**
+   * On `focus`, add the `focus-ring` class to the target if:
+   * - the target received focus as a result of keyboard navigation
```
Comment (alice) [inline src/focus-ring.js]: s/navigation/navigation, or/

File: src/focus-ring.js [hunk 4]
```diff
@@ -128,26 +131,75 @@ function init() {
...
       // Keep a reference to the element to which the focus-ring class is applied
       // so the focus-ring class can be restored to it if the window regains
       // focus after being blurred.
       elWithFocusRing = document.activeElement;
     }
   }
 
-  document.addEventListener('keyup', onKeyUp, true);
+  /**
+   * Add a group of listeners to detect a fine-grained pointing device.
```
Comment (alice) [inline src/focus-ring.js]: touch isn't fine grained, is it? I think this is just "usage of any pointing device".

File: src/focus-ring.js [hunk 5]
```diff
@@ -128,26 +131,75 @@ function init() {
...
+   * These listeners will be added when the polyfill first loads, and if
+   * the window is blurred and regains focus.
```
Comment (alice) [inline src/focus-ring.js]: s/and if the window is blurred and regains focus/and any time the window is blurred, so that they are active when the window regains focus./

File: src/focus-ring.js [hunk 6]
```diff
@@ -128,26 +131,75 @@ function init() {
...
+    document.addEventListener('pointerdown', onInitialPointerMove);
+    document.addEventListener('pointerup', onInitialPointerMove);
+    document.addEventListener('touchmove', onInitialPointerMove);
+    document.addEventListener('touchstart', onInitialPointerMove);
+    document.addEventListener('touchend', onInitialPointerMove);
+  }
+
+  /**
+   * When the polfyill first loads, assume the user is in keyboard modality.
+   * If any event is received from a fine-grained pointing device (mouse, pointer, touch),
```
Comment (alice) [inline src/focus-ring.js]: Again, touch isn't fine-grained.

File: src/focus-ring.js (hunk 4 above)
Comment (alice) [reply src/focus-ring.js]: https://drafts.csswg.org/mediaqueries-4/#valdef-media-pointer-coarse

"Examples include touchscreens ..."

File: src/focus-ring.js [hunk 7]
```diff
@@ -128,26 +131,75 @@ function init() {
...
+   * turn off keyboard modality.
+   * This accounts for situations where focus enters the page from the URL bar.
+   * In that scenario, the keydown event is inconsistent, so we can't use it to detect modality.
```
Comment (alice) [inline src/focus-ring.js]: I would delete this and the following two lines - more justification than necessary.

File: test/index.js [hunk 8]
```diff
@@ -85,7 +85,7 @@ function runMocha(driver, mocha) {
  */
 function browserFilter(browser) {
   return browser.getReleaseName() === 'stable'
-    && ['firefox', 'chrome'].includes(browser.getId());
+    && ['chrome', 'firefox'].includes(browser.getId());
```
Comment (alice) [inline test/index.js]: 🤔

File: test/fixtures/contenteditable-textbox.html [hunk 9]
```diff
@@ -20,6 +20,12 @@
     </style>
   </head>
   <body>
+    <!--
+      FF won't focus a div with contenteditable if it's the first element on the page.
+      https://jsbin.com/cawevo/edit?html,output
+      Add a dummy button so Selenium can use it as the first focus target.
+    -->
+    <button id="start">Dummy</button>
```
Comment (alice) [inline test/fixtures/contenteditable-textbox.html]: It confused me a little that the id was "start" but the contents was "Dummy".

File: test/specs/contenteditable-textbox.js [hunk 10]
```diff
@@ -1,18 +1,26 @@
...
-    return fixture('contenteditable-true.html');
+    return fixture('contenteditable-textbox.html');
   });
 
-  // This test seems to fail because FF won't focus a div with contenteditable
-  // if it's the first element on the page. Weird.
-  // https://jsbin.com/cawevo/edit?html,output
-  it.skip('should apply .focus-ring on keyboard focus', function() {
-    return matchesKeyboard();
+  // FF won't focus a div with contenteditable if it's the first element on the page.
```
Comment (alice) [inline test/specs/contenteditable-textbox.js]: That sounds like it was a lot of fun to debug 🙄

File: src/focus-ring.js [hunk 11]
```diff
@@ -1,17 +1,12 @@
...
 
 /**
  * https://github.com/WICG/focus-ring
  */
 function init() {
+  var hadKeyboardEvent = true;
   var elWithFocusRing;
 
   var inputTypesWhitelist = {
-    'radio': true,
```
[the remark this answers is not in the document]
Comment (robdodson) [reply src/focus-ring.js]: I don't think so. That would cause focus-ring to be applied on mouse click because these get checked during the focus event. The reverted version added them because it was checking only on keyUp.

File: src/focus-ring.js [hunk 12]
```diff
@@ -70,32 +65,43 @@ function init() {
...
-   *    keyboard navigation.
-   * 2. Unlike `focus`, keyup` will fire when the user navigates from the
-   *    browser chrome into the document. (For more, see issue #15)
+   * On `keydown`, set `hadKeyboardEvent`, add `focus-ring` class if the
+   * key was Tab/Shift-Tab or Arrow Keys.
    * @param {Event} e
    */
-  function onKeyUp(e) {
+  function onKeyDown(e) {
+    const allowedKeys = [9, 37, 38, 39, 40];
```
[the remark this answers is not in the document]
Comment (robdodson) [reply src/focus-ring.js]: There's a comment above that indicates it's tab and arrow keys but yeah.

File: src/focus-ring.js (hunk 1 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: src/focus-ring.js (hunk 2 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: src/focus-ring.js (hunk 4 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: src/focus-ring.js (hunk 5 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: src/focus-ring.js (hunk 3 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: src/focus-ring.js (hunk 6 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: src/focus-ring.js (hunk 7 above)
Comment (robdodson) [reply src/focus-ring.js]: Fixed

File: test/fixtures/contenteditable-textbox.html (hunk 9 above)
Comment (robdodson) [reply test/fixtures/contenteditable-textbox.html]: Fixed

File: test/index.js (hunk 8 above)
Comment (robdodson) [reply test/index.js]: was just double checking something. selenium-assistant stopped killing firefox 57 properly and I wasn't sure if the order in which the browsers opened/closed had anything to do with it. turns out it doesn't. the ordering doesn't matter and the issue isn't actually a show stopper. it just means if you test locally you need to close firefox when you're done. doesn't seem to bother travis though. I filed https://github.com/GoogleChromeLabs/selenium-assistant/issues/105

File: test/specs/contenteditable-textbox.js (hunk 10 above)
Comment (robdodson) [reply test/specs/contenteditable-textbox.js]: Not as much fun as https://github.com/WICG/focus-ring/pull/68/files#diff-6d1daa3464793cab0c4c5d8eeb17e778R178
